name: sree_assesments
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter_bloc: ^8.1.3
  http: ^1.2.0
  responsive_sizer: ^3.3.0+1
  build_runner: ^2.4.8
  json_annotation: ^4.8.1
  html: ^0.15.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  analyzer: ^5.11.1

flutter:
  uses-material-design: true
